packages:
  - products/*
  - docs

catalog:
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  typescript: 5.9.2
  vitest: ^3.2.4
  prettier: ^3.6.2

catalogs:
  backend:
    '@hono/node-server': ^1.19.2
    '@types/node': ^24.4.0
    hono: ^4.9.7
    tsx: ^4.20.5
  docs:
    '@astrojs/check': ^0.9.4
    astro: ^5.13.7
    prettier-plugin-astro: ^0.14.1
  frontend:
    '@eslint/js': ^9.35.0
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    '@vitejs/plugin-react-swc': ^4.0.1
    eslint: ^9.35.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    globals: ^16.4.0
    happy-dom: ^18.0.1
    react: ^19.1.1
    react-dom: ^19.1.1
    typescript-eslint: ^8.43.0
    vite: ^7.1.5
  root:
    turbo: ^2.5.6

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
