name: deploy-backend

permissions:
  contents: read

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build Check debt-manager
      - name: Build Check debt-manager
        run: nix develop --command bash -c "pnpm i && pnpm run build"
      # Replace database_id in backend/wrangler.jsonc
      - name: Replace database_id in backend/wrangler.jsonc
        run: |
          sed -i "s/\"database_id\": \".*\"/\"database_id\": \"hello-world!\"/" products/backend/wrangler.jsonc
      # Read
      - name: Read database_id
        run: |
          cat products/backend/wrangler.jsonc
      # Build & Deploy Backend to Cloudflare Workers
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "products/backend"
