name: dev-test

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
  workflow_dispatch:

jobs:
  dev-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build Check debt-manager
      - name: Build Check debt-manager
        run: nix develop --command bash -c "pnpm i && pnpm run build"
      # Test debt-manager
      - name: Test debt-manager
        run: nix develop --command bash -c "pnpm run test"
